environments:
  - name: production
    vpcCidrBlock: 10.0.0.0/16
    subnetCidrBlock: 10.0.0.0/24
  - name: staging
    vpcCidrBlock: 10.1.0.0/16
    subnetCidrBlock: 10.1.0.0/24


redshiftCluster:
  dbName: app
  nodeType: dc2.larger
  numberOfNodes: 2
  securityGroup:
    whiteListedIps:
      - 35.190.215.9/32
