name: Deploy S3 Bucket using jinga and workflow

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2

      - name: Setup Python
        uses: action/setup-python@v2
        with:
          python-version: '3.x'

      -name: Install Dependencies
        run: |
          pip install -r requeriments.txt
          pip install -r tests/requirements.txt

      - name: Run Tests
        run: python -m pytest


